export const placementFacts = [
  "💡 Did you know? 99% of VIT students claim they have a 9+ CGPA during placements",
  "💡 Fun fact: Every VITian has 'Full Stack Developer' in their resume",
  "💡 Placement tip: Wearing formal clothes increases placement chances by 0.01%",
  "💡 Remember: Your resume should be EXACTLY 1 page (1.01 pages = rejection)",
  "💡 Pro tip: Having an iPhone during placements doesn't guarantee Apple will hire you",
  "💡 Fact: 'Open to relocate anywhere' means Bangalore, Pune, or Hyderabad only",
  "💡 Truth: Everyone's 'Major Project' is actually from GitHub",
  "💡 Reality: Your CGPA will be checked 47 times before the interview",
  "💡 Wisdom: Saying 'I'm a quick learner' doesn't hide your resume gaps",
  "💡 Secret: Mass recruiters judge you by your handwriting in the aptitude test",
  "💡 Fact: Having 'Team Leader' for every project looks suspicious",
  "💡 Reality: Off-campus placements need 10x more effort but same LinkedIn flex",
  "💡 Truth: Your 10th percentage will haunt you till your last placement",
  "💡 Fact: Service-based companies have better food in their interviews",
  "💡 Pro tip: LinkedIn posts about 'Day 1 at XYZ' start being drafted in first year",
  "💡 Breaking: Saying 'Hello World' in 5 languages doesn't make you multilingual",
  "💡 Alert: Your 'AI/ML project' is just scikit-learn with extra steps",
  "💡 News: Calculator app doesn't count as a project (seriously, stop)",
  "💡 Tip: 'Proficient in MS Office' is not a technical skill in 2024",
  "💡 Reality: Your GitHub green squares are all from README updates",
  "💡 Fact: Hackathon participation certificates > Actual hackathon wins",
  "💡 Truth: Everyone knows you Googled the coding round answers",
  "💡 Warning: Your 'currently learning' section has been 'current' for 2 years",
  "💡 Secret: HR can tell when you're reading from ChatGPT in interviews",
  "💡 Discovery: Listing 'HTML' as a programming language is a war crime",
  "💡 Insight: Your resume's 'Hobbies' section won't save you",
  "💡 Alert: Companies can see when you change 'Currently working' to 'Actively looking'",
  "💡 Fact: Your placement group has 2000 messages/day, 1999 are panicking",
  "💡 Reality: 'Flexible with salary' means you'll take anything at this point",
  "💡 Truth: Bond agreements are written in font size 6 for a reason",
  "💡 VIT Pune Special: Audi events scheduled during placement prep are a tradition",
  "💡 Pune Life: AC breaks down only during mandatory formal dress events",
  "💡 Reality Check: You'll attend more audi events than actual classes this semester",
  "💡 Fact: VIT Pune has more audis than placement opportunities (just kidding... or are we?)",
  "💡 Truth: The walk from one audi to another is your daily cardio",
  "💡 Discovery: Photoshoot smile practice is harder than technical interview prep",
  "💡 Wisdom: Rehearsal for 4 hours, actual event for 10 minutes - VIT Pune efficiency",
  "💡 Alert: Random audi event attendance affects your placement eligibility (somehow)",
  "💡 Secret: Best placement prep happens in audi when you should be listening",
  "💡 Fact: More cultural events than companies visiting - Priorities sorted!"
];

export function getRandomFact(): string {
  return placementFacts[Math.floor(Math.random() * placementFacts.length)];
}
